compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
deepspeed_config:
 deepspeed_config_file: scripts/accelerate_configs/zero.json
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: 29504
main_training_function: main
num_machines: 1
num_processes: 2
gpu_ids: 1, 2
use_cpu: false
